from utils.database import db
import datetime

# Decription: The table stores User details. Here id is gamename which can be empid or phone number
class Users(db.Model):
    __tablename__ = 'users'
    #__table_args__ = {"schema": "puzzlegame"
    id = db.Column(db.Integer, primary_key=True)
    firstName = db.Column(db.String(80), nullable=False)
    familyName = db.Column(db.String(80))
    pin = db.Column(db.Integer, nullable=False)
    isAdmin = db.Column(db.Boolean, nullable=False, default=False)
    submissions = db.relationship('Submissions', backref='users', lazy='dynamic')
    marks = db.relationship('Leaderboard', backref='users', lazy='dynamic')

# Decription: The table stores the solved and the next question for each user. Each time an 
# user sends a correct answer, the question's isSolved value is changed to True and 
# a new row gets created for the next question with isSolved value as false
class Submissions(db.Model):
    __tablename__ = 'submissions'
    #__table_args__ = {"schema": "puzzlegame"}
    userId = db.Column(db.Integer, db.ForeignKey('users.id'), primary_key=True, nullable=False)
    questionNum = db.Column(db.Integer, nullable=False, primary_key=True)
    isSolved = db.Column(db.Boolean, nullable=False, default=False)
    appearingTime = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)
    submissionTime = db.Column(db.DateTime, nullable=True)
    submissionCount = db.Column(db.Integer, nullable=False, default=0)

# Decription: The table stores an autogenerated sequence of question for each user
class QuestionSequence(db.Model):
    __tablename__ = 'question_sequence'
    #__table_args__ = {"schema": "puzzlegame"}
    # This table stores the question sequence in which the questions needs to be displayed for an user
    userId = db.Column(db.Integer, db.ForeignKey('users.id'), primary_key=True, nullable=False)
    sequence = db.Column(db.String(80))

# Decription: The table stores the marks obtained by each user
class Leaderboard(db.Model):
    __tablename__ = 'leaderboard'
    #__table_args__ = {"schema": "puzzlegame"}
    userId = db.Column(db.Integer, db.ForeignKey('users.id'), primary_key=True, nullable=False)
    marks = db.Column(db.Float, nullable=False, default=0.0)
    marks2 = db.Column(db.Integer, nullable=False, default=0.0)
    milestoneCount = db.Column(db.Integer, nullable=False, default=0)

# Decription: The table will store all the correct and incorrect answers given by an user
class SubmissionDetails(db.Model):
    __tablename__ = 'submission_details'
    submissionId = db.Column(db.Integer, primary_key=True, nullable=False, autoincrement=True)
    userId = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    questionNum = db.Column(db.Integer)
    submittedAnswer = db.Column(db.String(80))
    submissionTime = db.Column(db.DateTime, nullable=True, default=datetime.datetime.utcnow)

class Competitions(db.Model):
    __tablename__ = 'competitions'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    startTime = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)
    isActive = db.Column(db.Boolean, nullable=False, default=True)


db.create_all()
# db.drop_all()

db.session.commit()

